export const tiers = {
  "0": {
    "points": 50,
    "pokemon": [
      "Bulbasaur",
      "Charmander",
      "Squirtle",
      "Eevee",
      "Porygon",
      "Snorlax",
      "Chikorita",
      "Cyndaquil",
      "Totodile",
      "Togepi",
      "Tyrogue",
      "Treecko",
      "Torchic",
      "Mudkip",
      "Shedinja",
      "Beldum",
      "Turtwig",
      "Chimchar",
      "Piplup",
      "Riolu",
      "Rotom",
      "Snivy",
      "Tepig",
      "Oshawott"
    ]
  },
  "1": {
    "points": 45,
    "pokemon": [
      "Chansey",
      "Kangaskhan",
      "Scyther",
      "Pinsir",
      "Sudowoodo",
      "Skarmory",
      "Shroomish",
      "Slakoth",
      "Skitty",
      "Plusle",
      "Minun",
      "Gulpin",
      "Castform",
      "Absol",
      "Burmy",
      "Combee",
      "Cherubi",
      "Spiritomb",
      "Skorupi",
      "Carnivine",
      "Pansage",
      "Pansear",
      "Panpour",
      "Drilbur",
      "Audino",
      "Ducklett",
      "Emolga",
      "Alomomola",
      "Larvesta"
    ]
  },
  "2": {
    "points": 40,
    "pokemon": [
      "Clefairy",
      "Shellder",
      "Mr. Mime",
      "Lapras",
      "Omanyte",
      "Kabuto",
      "Aerodactyl",
      "Aipom",
      "Pineco",
      "Qwilfish",
      "Shuckle",
      "Corsola",
      "Houndour",
      "Miltank",
      "Ralts",
      "Nincada",
      "Lileep",
      "Anorith",
      "Feebas",
      "Relicanth",
      "Bagon",
      "Cranidos",
      "Shieldon",
      "Tirtouga",
      "Archen",
      "Zorua",
      "Pawniard"
    ]
  },
  "3": {
    "points": 30,
    "pokemon": [
      "Vulpix",
      "Growlithe",
      "Farfetch'd",
      "Exeggcute",
      "Staryu",
      "Jynx",
      "Magmar",
      "Tauros",
      "Dratini",
      "Sentret",
      "Ledyba",
      "Sunkern",
      "Yanma",
      "Murkrow",
      "Spinda",
      "Trapinch",
      "Gligar",
      "Heracross",
      "Remoraid",
      "Delibird",
      "Mantine",
      "Nosepass",
      "Volbeat",
      "Illumise",
      "Carvanha",
      "Wailmer",
      "Cacnea",
      "Zangoose",
      "Seviper",
      "Barboach",
      "Kecleon",
      "Tropius",
      "Chimecho",
      "Luvdisc",
      "Drifloon",
      "Stunky",
      "Chatot",
      "Gible",
      "Croagunk",
      "Finneon",
      "Darumaka",
      "Maractus",
      "Sigilyph",
      "Cryogonal"
    ]
  },
  "4": {
    "points": 15,
    "pokemon": [
      "Oddish",
      "Venonat",
      "Meowth",
      "Drowzee",
      "Electabuzz",
      "Hoothoot",
      "Spinarak",
      "Wooper",
      "Snubbull",
      "Sneasel",
      "Larvitar",
      "Lotad",
      "Surskit",
      "Spinda",
      "Trapinch",
      "Lunatone",
      "Corphish",
      "Kricketot",
      "Pachirisu",
      "Buneary",
      "Purrloin",
      "Pidove",
      "Scraggy",
      "Axew",
      "Bouffalant",
      "Rufflet",
      "Heatmor",
      "Deino"
    ]
  },
  "5": {
    "points": 10,
    "pokemon": [
      "Caterpie",
      "Weedle",
      "Pikachu",
      "Nidoran [M]",
      "Jigglypuff",
      "Paras",
      "Bellsprout",
      "Horsea",
      "Natu",
      "Hoppip",
      "Teddiursa",
      "Wurmple",
      "Taillow",
      "Numel",
      "Swablu",
      "Snorunt",
      "Starly",
      "Hippopotas",
      "Lillipup",
      "Timburr",
      "Throh",
      "Sawk",
      "Venipede",
      "Cottonee",
      "Petilil",
      "Dwebble",
      "Trubbish",
      "Karrablast",
      "Foongus",
      "Joltik",
      "Ferroseed",
      "Tynamo",
      "Cubchoo",
      "Shelmet"
    ]
  },
  "6": {
    "points": 5,
    "pokemon": [
      "Pidgey",
      "Spearow",
      "Ekans",
      "Nidoran [F]",
      "Diglett",
      "Mankey",
      "Abra",
      "Ponyta",
      "Doduo",
      "Grimer",
      "Cubone",
      "Lickitung",
      "Tangela",
      "Ditto",
      "Chinchou",
      "Mareep",
      "Slugma",
      "Stantler",
      "Poochyena",
      "Zigzagoon",
      "Wingull",
      "Whismur",
      "Makuhita",
      "Sableye",
      "Aron",
      "Electrike",
      "Roselia",
      "Spoink",
      "Solrock",
      "Clamperl",
      "Duskull",
      "Bidoof",
      "Shinx",
      "Snover",
      "Patrat",
      "Munna",
      "Blitzle",
      "Roggenrola",
      "Woobat",
      "Tympole",
      "Sewaddle",
      "Minccino",
      "Gothita",
      "Solosis",
      "Vanillite",
      "Klink",
      "Elgyem",
      "Stunfisk",
      "Druddigon",
      "Vullaby",
      "Durant"
    ]
  },
  "7": {
    "points": 3,
    "pokemon": [
      "Rattata",
      "Sandshrew",
      "Zubat",
      "Psyduck",
      "Poliwag",
      "Machop",
      "Tentacool",
      "Geodude",
      "Slowpoke",
      "Magnemite",
      "Seel",
      "Gastly",
      "Onix",
      "Krabby",
      "Voltorb",
      "Koffing",
      "Rhyhorn",
      "Goldeen",
      "Magikarp",
      "Marill",
      "Unown",
      "Wobbuffet",
      "Girafarig",
      "Dunsparce",
      "Swinub",
      "Smeargle",
      "Seedot",
      "Meditite",
      "Torkoal",
      "Baltoy",
      "Shuppet",
      "Duskull",
      "Spheal",
      "Buizel",
      "Shellos",
      "Glameow",
      "Bronzor",
      "Basculin",
      "Sandile",
      "Yamask",
      "Deerling",
      "Frillish",
      "Litwick",
      "Mienfoo",
      "Golett"
    ]
  }
} as const;

export const dex: Record<string, number> = {
  "Bulbasaur": 1,
  "Charmander": 4,
  "Squirtle": 7,
  "Eevee": 133,
  "Porygon": 137,
  "Snorlax": 143,
  "Chikorita": 152,
  "Cyndaquil": 155,
  "Totodile": 158,
  "Togepi": 175,
  "Tyrogue": 236,
  "Treecko": 252,
  "Torchic": 255,
  "Mudkip": 258,
  "Shedinja": 292,
  "Beldum": 374,
  "Turtwig": 387,
  "Chimchar": 390,
  "Piplup": 393,
  "Riolu": 447,
  "Rotom": 479,
  "Snivy": 495,
  "Tepig": 498,
  "Oshawott": 501,
  "Chansey": 113,
  "Kangaskhan": 115,
  "Scyther": 123,
  "Pinsir": 127,
  "Sudowoodo": 185,
  "Skarmory": 227,
  "Shroomish": 285,
  "Slakoth": 287,
  "Skitty": 300,
  "Plusle": 311,
  "Minun": 312,
  "Gulpin": 316,
  "Castform": 351,
  "Absol": 359,
  "Burmy": 412,
  "Combee": 415,
  "Cherubi": 420,
  "Spiritomb": 442,
  "Skorupi": 451,
  "Carnivine": 455,
  "Pansage": 511,
  "Pansear": 513,
  "Panpour": 515,
  "Drilbur": 529,
  "Audino": 531,
  "Ducklett": 580,
  "Emolga": 587,
  "Alomomola": 594,
  "Larvesta": 636,
  "Clefairy": 35,
  "Shellder": 90,
  "Mr. Mime": 122,
  "Lapras": 131,
  "Omanyte": 138,
  "Kabuto": 140,
  "Aerodactyl": 142,
  "Aipom": 190,
  "Pineco": 204,
  "Qwilfish": 211,
  "Shuckle": 213,
  "Corsola": 222,
  "Houndour": 228,
  "Miltank": 241,
  "Ralts": 280,
  "Nincada": 290,
  "Lileep": 345,
  "Anorith": 347,
  "Feebas": 349,
  "Relicanth": 369,
  "Bagon": 371,
  "Cranidos": 408,
  "Shieldon": 410,
  "Tirtouga": 564,
  "Archen": 566,
  "Zorua": 570,
  "Pawniard": 624,
  "Vulpix": 37,
  "Growlithe": 58,
  "Farfetch'd": 83,
  "Exeggcute": 102,
  "Staryu": 120,
  "Jynx": 124,
  "Magmar": 126,
  "Tauros": 128,
  "Dratini": 147,
  "Sentret": 161,
  "Ledyba": 165,
  "Sunkern": 191,
  "Yanma": 193,
  "Murkrow": 198,
  "Spinda": 327,
  "Trapinch": 328,
  "Gligar": 207,
  "Heracross": 214,
  "Remoraid": 223,
  "Delibird": 225,
  "Mantine": 226,
  "Nosepass": 299,
  "Volbeat": 313,
  "Illumise": 314,
  "Carvanha": 318,
  "Wailmer": 320,
  "Cacnea": 331,
  "Zangoose": 335,
  "Seviper": 336,
  "Barboach": 339,
  "Kecleon": 352,
  "Tropius": 357,
  "Chimecho": 358,
  "Luvdisc": 370,
  "Drifloon": 425,
  "Stunky": 434,
  "Chatot": 441,
  "Gible": 443,
  "Croagunk": 453,
  "Finneon": 456,
  "Darumaka": 554,
  "Maractus": 556,
  "Sigilyph": 561,
  "Cryogonal": 615,
  "Oddish": 43,
  "Venonat": 48,
  "Meowth": 52,
  "Drowzee": 96,
  "Electabuzz": 125,
  "Hoothoot": 163,
  "Spinarak": 167,
  "Wooper": 194,
  "Snubbull": 209,
  "Sneasel": 215,
  "Larvitar": 246,
  "Lotad": 270,
  "Surskit": 283,
  "Lunatone": 337,
  "Corphish": 341,
  "Kricketot": 401,
  "Pachirisu": 417,
  "Buneary": 427,
  "Purrloin": 509,
  "Pidove": 519,
  "Scraggy": 559,
  "Axew": 610,
  "Bouffalant": 626,
  "Rufflet": 627,
  "Heatmor": 631,
  "Deino": 633,
  "Caterpie": 10,
  "Weedle": 13,
  "Pikachu": 25,
  "Nidoran [M]": 32,
  "Jigglypuff": 39,
  "Paras": 46,
  "Bellsprout": 69,
  "Horsea": 116,
  "Natu": 177,
  "Hoppip": 187,
  "Teddiursa": 216,
  "Wurmple": 265,
  "Taillow": 276,
  "Numel": 322,
  "Swablu": 333,
  "Snorunt": 361,
  "Starly": 396,
  "Hippopotas": 449,
  "Lillipup": 506,
  "Timburr": 532,
  "Throh": 538,
  "Sawk": 539,
  "Venipede": 543,
  "Cottonee": 546,
  "Petilil": 548,
  "Dwebble": 557,
  "Trubbish": 568,
  "Karrablast": 588,
  "Foongus": 590,
  "Joltik": 595,
  "Ferroseed": 597,
  "Tynamo": 602,
  "Cubchoo": 613,
  "Shelmet": 616,
  "Pidgey": 16,
  "Spearow": 21,
  "Ekans": 23,
  "Nidoran [F]": 29,
  "Diglett": 50,
  "Mankey": 56,
  "Abra": 63,
  "Ponyta": 77,
  "Doduo": 84,
  "Grimer": 88,
  "Cubone": 104,
  "Lickitung": 108,
  "Tangela": 114,
  "Ditto": 132,
  "Chinchou": 170,
  "Mareep": 179,
  "Slugma": 218,
  "Stantler": 234,
  "Poochyena": 261,
  "Zigzagoon": 263,
  "Wingull": 278,
  "Whismur": 293,
  "Makuhita": 296,
  "Sableye": 302,
  "Aron": 304,
  "Electrike": 309,
  "Roselia": 315,
  "Spoink": 325,
  "Solrock": 338,
  "Clamperl": 366,
  "Duskull": 355,
  "Bidoof": 399,
  "Shinx": 403,
  "Snover": 459,
  "Patrat": 504,
  "Munna": 517,
  "Blitzle": 522,
  "Roggenrola": 524,
  "Woobat": 527,
  "Tympole": 535,
  "Sewaddle": 540,
  "Minccino": 572,
  "Gothita": 574,
  "Solosis": 577,
  "Vanillite": 582,
  "Klink": 599,
  "Elgyem": 605,
  "Stunfisk": 618,
  "Druddigon": 621,
  "Vullaby": 629,
  "Durant": 632,
  "Rattata": 19,
  "Sandshrew": 27,
  "Zubat": 41,
  "Psyduck": 54,
  "Poliwag": 60,
  "Machop": 66,
  "Tentacool": 72,
  "Geodude": 74,
  "Slowpoke": 79,
  "Magnemite": 81,
  "Seel": 86,
  "Gastly": 92,
  "Onix": 95,
  "Krabby": 98,
  "Voltorb": 100,
  "Koffing": 109,
  "Rhyhorn": 111,
  "Goldeen": 118,
  "Magikarp": 129,
  "Marill": 183,
  "Unown": 201,
  "Wobbuffet": 202,
  "Girafarig": 203,
  "Dunsparce": 206,
  "Swinub": 220,
  "Smeargle": 235,
  "Seedot": 273,
  "Meditite": 307,
  "Torkoal": 324,
  "Baltoy": 343,
  "Shuppet": 353,
  "Spheal": 363,
  "Buizel": 418,
  "Shellos": 422,
  "Glameow": 431,
  "Bronzor": 436,
  "Basculin": 550,
  "Sandile": 551,
  "Yamask": 562,
  "Deerling": 585,
  "Frillish": 592,
  "Litwick": 607,
  "Mienfoo": 619,
  "Golett": 622
};
